library(here)
library(rcarbon)
load(here('data','c14demo.RData'))
c14db <- subset(c14db,Region%in%c('Tokai','Chubu'))
c14db$Region[which(c14db$Region=='Chubu')] <- 'Chubu Highlands'
c14.cal  <- calibrate(c14db$C14Age,c14db$C14Error,normalised=T)
bins  <- binPrep(sites=c14db$SiteID,ages=c14.cal,h=50)
spds <- stackspd(c14.cal,timeRange=BCADtoBP(c(-950,250)),bins = bins,group = c14db$Region)
plot(spds,'multipanel',calendar='BCAD',rescale=T)
test <- permTest(x=c14.cal,marks=c14db$Region,bins=bins,timeRange=BCADtoBP(c(-950,250)),nsim=5000)
plot(test,2)
